log_format json_log escape=json
    '{"time":"$time_iso8601",'
     '"service":"user-manager-client",'
     '"remote_addr":"$remote_addr",'
     '"method":"$request_method",'
     '"uri":"$request_uri",'
     '"status":$status,'
     '"body_bytes_sent":$body_bytes_sent,'
     '"request_time":$request_time,'
     '"user_agent":"$http_user_agent"}';

server {
    listen 80;

    access_log /var/log/nginx/access.log json_log;
    error_log  /var/log/nginx/error.log warn;

    location /users {
        proxy_pass http://user-manager-server:8000;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
}
